<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.truong</groupId>
	<artifactId>com.truong</artifactId>
	<version>1.0.1.RELEASE</version>
	<packaging>pom</packaging>

	<name>com.truong</name>
	<description>test</description>

	<properties>
		<java.version>17</java.version>
		
		<spring-boot.version>3.2.5</spring-boot.version>
		
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
	</properties>

	<modules>
		<module>com.truong.oauth</module>
		<module>com.truong.restapi</module>
		<module>com.truong.entity</module>
		<module>com.truong.service</module>
		<module>com.truong.dao</module>
		<module>com.truong.configuration</module>
		<module>com.truong.common</module>
		<module>com.truong.kafka</module>
		<module>com.truong.redis</module>
		<module>com.truong.media</module>
	</modules>
	
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			
			<dependency>
	            <groupId>org.apache.httpcomponents.client5</groupId>
	            <artifactId>httpcomponents-client5</artifactId>
	            <version>5.2.1</version>
	        </dependency>
		</dependencies>
		
		
	</dependencyManagement>

</project>