spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

project.oauth.port = 9001
project.restapi.port = 9002

oauth2.endpoint = http://localhost:9001/oauth/token

spring.datasource.master.url=jdbc:mysql://localhost:3306/mydatabase
spring.datasource.master.username=root
spring.datasource.master.password=11112222

spring.datasource.slave.url=jdbc:mysql://localhost:3307/mydatabase
spring.datasource.slave.username=root
spring.datasource.slave.password=33334444



spring.kafka.bootstrap-servers = http://172.16.10.95:9092



spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=123456
spring.redis.database=1



spring.datasource.url=jdbc:mysql://localhost:6603/test
spring.datasource.username=root
spring.datasource.password=11111111

hibernate.dialect = org.hibernate.dialect.MySQLDialect
hibernate.show_sql = false
hibernate.format_sql = true
hibernate.current_session_context_class = org.springframework.orm.hibernate5.SpringSessionContext
hikaricp.connectionTimeout = 30000
hikaricp.idleTimeout = 600000
hikaricp.maxLifetime = 1800000
hikaricp.maximumPoolSize = 2
hikaricp.minimumIdle = 1
hikaricp.cachePrepStmts = true
hikaricp.cacheResultSetMetadata = true
hikaricp.cacheServerConfiguration = true
hikaricp.prepStmtCacheSize = 250
hikaricp.prepStmtCacheSqlLimit = 2048
hikaricp.useServerPrepStmts = true
hikaricp.useLocalSessionState = true
hikaricp.rewriteBatchedStatements = true
hikaricp.elideSetAutoCommit = true
hikaricp.maintainTimeStats = false


oauth2.authorization-server.issuer=http://localhost:9001
oauth2.authorization-server.key-id=main-key
oauth2.authorization-server.rsa-private-key=-----BEGIN PRIVATE KEY-----\
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC2XIC2TqJGmzZV\
saDYv/ZPOGFA2pvoZvk1woPscWKwhcIWXnv7lEYhGJRZClwPcHOpeyT/fbYFN4gm\
Ww0vJAa+3qVjpdae1gBRKA88vQusNV0+Pn+GjewNxOv5G8TpBBASIC924/LZncY7\
cTUO/uY4J5xtwsL6z/Z0Z01VEEbmuynhfCPjEo6wHX5KE/rw2VryU2Y4xAEw1gn3\
Q4O94cR75DFq9WN+iwhUsLJZ96raCKzrTwW/4TI7Gof1CHHw2EJ7SWlRXdHIjxA2\
9+d/IlZf/IZZ6MFjReHfx15XAkdRgkFHgN1cH5sPNO1RRLiKIKz8xZPlEHlVQW7e\
C7bGvSONAgMBAAECggEACpUFlw6rFgPNvF1JYyqIhYJVCmllILBRB9CYzTCrNGke\
oSOseCXbh/IgMaaLPw4ceBpARF8sH9NgIDGqazDg/1R2LnkiIidy70Ku16x0r/KM\
zZ7c0ZcMuqPRuavl2ku1Dwg1GOYTYpNoPGzOUmdyPpH13tytadaFi62u7B+8rYjX\
yr128N2IzaoR2O9xJCItndnLej5ltHexvt8y5vQ2ArgH59/y1hD8jzHXXHSA6rzd\
9JQFC0oL6xP9McO1CAfdZZFWNW+TgT4OpjTvdMAvqieGbb+4aGPK+CjhfLpOvrQJ\
QKvfLbvwcY7njrBcElPWGKMXpTJXHy2VWnx/Vu5pYQKBgQDY8vYPNN1DmTlYRR1S\
xA5gjKczBzM1Y/bRB3nNvAszrRs6CIWelUyPsq448H/fAtsk0lOnUk0WDIOxq95A\
JYAPe0lEGfEpo2OEEFPEl9HLIbDa6CDbt68cdjlLLVt12EagrilM/6ZibnU4uOkF\
sEKHjqNPSpWbLvhcGO22GibySQKBgQDXL7woC4rfktPBpueSut+6YN2WWK8ooxwP\
omENCRm/qfX1TdkR2fmzQJPWfTNPwyHoIGNlebBvk8Uy7Z9ndlUS7casVWTrZ8Y+\
ybTrqKsOFNEMoRfsqeR/APUGEASw9aVzLk1ozm4rZpCk8CSVY1Tt3P1K+pttS1Ql\
AfrxbpsnJQKBgHzecuPTwJr84TW+Kh+OOtw1eLL1LPNJAzHSxLe2yRfIRgiECSx6\
sGNxK7gYLPFWOn4aFQ4UX8wWDeLAkp6HNwsyIbxx1g3qPggwQZbA736keJ+2xdrR\
AZg3L8jmZWMRxa0MMTdhWgoDm7K3M2AT0GcnoTWtLyjvwwF3U7LhoJMJAoGBAKVI\
EvunMfnb6y5ZJpG7W9DqSgkLAS7zacBQdr7ueIqQ30yViN9/T53xQhyDegAP32FO\
T0pIF87774HYppFvgJTTccA4rxVpVgowH/jKSui78H4E1j1/mPQ8JfeMIi5R380C\
iY6w0Eohs4Qct9zOuRMipKMMrolaTL1IMhlzXVTJAoGBALNWe6j+hYMVj6oi17Ik\
zvTuNDDMYH9Q6A0SwNLvhwlpfaHrJbNcoFBZp0bxcVg30diw5YMnD2rK57j7nRLh\
/iFoWK0AvBqTmB1FVCaX3h4IcF0V+2l1UV+LQpQCzCv5s92lpTVe8FIsNW8PIJoC\
wlyFvoQLhm0AB8RX+qXGpW+a\
-----END PRIVATE KEY-----
oauth2.authorization-server.rsa-public-key=-----BEGIN PUBLIC KEY-----\
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtlyAtk6iRps2VbGg2L/2\
TzhhQNqb6Gb5NcKD7HFisIXCFl57+5RGIRiUWQpcD3BzqXsk/322BTeIJlsNLyQG\
vt6lY6XWntYAUSgPPL0LrDVdPj5/ho3sDcTr+RvE6QQQEiAvduPy2Z3GO3E1Dv7m\
OCecbcLC+s/2dGdNVRBG5rsp4Xwj4xKOsB1+ShP68Nla8lNmOMQBMNYJ90ODveHE\
e+QxavVjfosIVLCyWfeq2gis608Fv+EyOxqH9Qhx8NhCe0lpUV3RyI8QNvfnfyJW\
X/yGWejBY0Xh38deVwJHUYJBR4DdXB+bDzTtUUS4iiCs/MWT5RB5VUFu3gu2xr0j\
jQIDAQAB\
-----END PUBLIC KEY-----
oauth2.token.access-token-ttl-seconds=3600
oauth2.token.refresh-token-ttl-seconds=2592000
oauth2.token.reuse-refresh-token=true